version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    networks:
      - internal
    volumes:
      - ./templates:/etc/nginx/templates
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    links:
      - php
  php:
    image: php:8-fpm
    networks:
      - internal
    volumes:
      - ./www:/var/www
      - ./conf/nginx.conf:/usr/local/etc/php-fpm.d/nginx.conf
networks:
  internal:
    driver: bridge
